// scripts/paths.ts
// Path normalisation and the reserved-path rules.
//
// This module exists on its own because it is the security boundary of the whole
// project: it is what stops a generated iteration from overwriting the consent
// script, a past archive entry, or anything outside site/. It is pure, so it is
// testable, and it is tested in scripts/__tests__/paths.test.ts.
//
// The rule that matters: ALWAYS normalise before comparing. The original
// implementation compared the raw string, so "./_/consent.js" and
// "x/../archive/2026-05-19/index.html" both slipped past.

import { posix } from 'path'

/** Directory prefixes the generator may never write into. */
export const RESERVED_PREFIXES = ['archive/', '_/', 'timeline/'] as const

/** Exact paths the generator may never write. */
export const RESERVED_EXACT = ['feed.xml', 'sitemap.xml', 'robots.txt'] as const

/**
 * Reference prefixes that are valid in generated HTML even though the target is
 * not one of the generated files, because the orchestrator produces them.
 * This list is why the original validator rejected legitimate iterations: it was
 * missing /timeline/ and the three generated XML/text files, both of which every
 * well-behaved iteration links to.
 */
export const INFRA_REF_PREFIXES = ['/assets/', '/_/', '/archive/', '/timeline/'] as const

/** Exact reference targets produced by the orchestrator. */
export const INFRA_REF_EXACT = ['/feed.xml', '/sitemap.xml', '/robots.txt'] as const

/**
 * Normalise a generator-supplied path to a canonical, comparable form:
 * POSIX separators, no "./" prefix, no redundant segments, no trailing slash.
 * Returns the normalised path. Does not decide legality — see assertWritablePath.
 */
export function normalisePath(input: string): string {
  const withPosixSeps = input.replace(/\\/g, '/')
  let normalised = posix.normalize(withPosixSeps)
  // posix.normalize leaves a leading "./" off already, but "./" alone becomes "."
  if (normalised === '.') return ''
  if (normalised.startsWith('./')) normalised = normalised.slice(2)
  if (normalised.length > 1 && normalised.endsWith('/')) normalised = normalised.slice(0, -1)
  return normalised
}

export class IllegalPathError extends Error {
  constructor(path: string, reason: string) {
    super(`Illegal generated path ${JSON.stringify(path)}: ${reason}`)
    this.name = 'IllegalPathError'
  }
}

/**
 * Throw unless `input` is a path the generator is allowed to write, relative to site/.
 * Returns the normalised path on success — callers should write to THAT, never to
 * the raw input, or the normalisation was pointless.
 */
export function assertWritablePath(input: string): string {
  if (typeof input !== 'string' || !input.trim()) {
    throw new IllegalPathError(String(input), 'path is empty')
  }
  if (input.includes('\0')) {
    throw new IllegalPathError(input, 'path contains a null byte')
  }
  if (input.startsWith('/')) {
    throw new IllegalPathError(input, 'absolute paths are not allowed')
  }
  if (/^[a-zA-Z]:/.test(input)) {
    throw new IllegalPathError(input, 'drive-letter paths are not allowed')
  }

  const normalised = normalisePath(input)

  if (!normalised) {
    throw new IllegalPathError(input, 'path normalises to nothing')
  }
  if (normalised === '..' || normalised.startsWith('../')) {
    throw new IllegalPathError(input, 'path escapes site/')
  }

  // The check the original got wrong: compare the NORMALISED path, so that
  // "./_/consent.js" and "x/../_/consent.js" are caught alongside "_/consent.js".
  for (const prefix of RESERVED_PREFIXES) {
    if (normalised === prefix.slice(0, -1) || normalised.startsWith(prefix)) {
      throw new IllegalPathError(input, `${prefix} is reserved for the orchestrator`)
    }
  }
  for (const exact of RESERVED_EXACT) {
    if (normalised === exact) {
      throw new IllegalPathError(input, `${exact} is generated by the orchestrator`)
    }
  }

  return normalised
}

/**
 * Resolve a reference found in an HTML file to a site-root-relative path.
 * `fromFile` is the site-relative path of the file containing the reference, so
 * that a relative href in sub/page.html resolves against sub/, not against the root.
 * Returns null for references that leave the site (http, protocol-relative,
 * mailto, tel, data, fragment-only).
 */
export function resolveReference(fromFile: string, ref: string): string | null {
  const trimmed = ref.trim()
  if (!trimmed) return null
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(trimmed)) return null // any scheme: http:, mailto:, data:, tel:
  if (trimmed.startsWith('//')) return null // protocol-relative
  if (trimmed.startsWith('#')) return null // same-page fragment

  const withoutQuery = trimmed.split('?')[0].split('#')[0]
  if (!withoutQuery) return null

  if (withoutQuery.startsWith('/')) {
    return posix.normalize(withoutQuery)
  }
  const dir = posix.dirname(fromFile)
  const joined = dir === '.' ? withoutQuery : posix.join(dir, withoutQuery)
  return '/' + normalisePath(joined)
}

/** True if a resolved reference points at something the orchestrator generates. */
export function isInfrastructureReference(resolved: string): boolean {
  if (INFRA_REF_EXACT.includes(resolved as typeof INFRA_REF_EXACT[number])) return true
  return INFRA_REF_PREFIXES.some(p => resolved.startsWith(p))
}
